[package]
name = "uklid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10.0"
filesize = "0.2.0"
fs_extra = "1.2.0"
human_bytes = "0.3.1"
walkdir = "2.3.2"
